[package]
name = "expenses"
version = "1.1.0"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.9", package = "gtk4", features = ["gnome_47"] }
rusqlite = { version = "0.34", features = ["bundled", "backup"] }
chrono = "0.4"
uuid = { version = "1", features = ["v4"] }
zip = { version = "2", default-features = false, features = ["deflate"] }

[dependencies.adw]
package = "libadwaita"
version = "0.7"
features = ["v1_6"]

[profile.release]
strip = true
lto = true
opt-level = "s"
